using System.Text.Json.Serialization;
using Confix.Extensions;
using Confix.Tool.Entities.Components.DotNet;
using Confix.Tool.Middlewares.Artifact;
using Confix.Tool.Middlewares.Project;
using Confix.Tool.Schema;
using Json.Schema;

namespace Confix.Tool.Abstractions;

public sealed class ProjectDefinition
{
    public const string DefaultName = "__Default";

    public ProjectDefinition(
        string name,
        IReadOnlyList<EnvironmentDefinition> environments,
        IReadOnlyList<ComponentReferenceDefinition> components,
        IReadOnlyList<ComponentRepositoryDefinition> repositories,
        IReadOnlyList<VariableProviderDefinition> variableProviders,
        IReadOnlyList<ComponentProviderDefinition> componentProviders,
        IReadOnlyList<ConfigurationFileDefinition> configurationFiles,
        IReadOnlyList<ProjectDefinition> subprojects,
        DirectoryInfo? directory)
    {
        Name = name;
        Environments = environments;
        Components = components;
        Repositories = repositories;
        VariableProviders = variableProviders;
        ComponentProviders = componentProviders;
        ConfigurationFiles = configurationFiles;
        Subprojects = subprojects;
        Directory = directory;
    }

    public string Name { get; }

    public IReadOnlyList<EnvironmentDefinition> Environments { get; }

    public IReadOnlyList<ComponentReferenceDefinition> Components { get; }

    public IReadOnlyList<ComponentRepositoryDefinition> Repositories { get; }

    public IReadOnlyList<VariableProviderDefinition> VariableProviders { get; }

    public IReadOnlyList<ComponentProviderDefinition> ComponentProviders { get; }

    public IReadOnlyList<ConfigurationFileDefinition> ConfigurationFiles { get; }

    public IReadOnlyList<ProjectDefinition> Subprojects { get; }

    public DirectoryInfo? Directory { get; }

    /// <summary>
    /// Stores the JSON schema of the project configuration file. This is used for validation. The
    /// JSON schema is empty until it loaded from the <see cref="ISchemaStore"/>, generated by the
    /// <see cref="ReloadProjectMiddleware"/> or loaded by the <see cref="ReadArtifactMiddleware"/>.
    /// </summary>
    public string? JsonSchema { get; set; }

    public static ProjectDefinition From(ProjectConfiguration configuration)
    {
        var lastConfigurationFile =
            configuration.SourceFiles.LastOrDefault(x => x.File.Name == FileNames.ConfixProject);

        var name = configuration.Name
            ?? lastConfigurationFile?.File.Directory?.Name
            ?? DefaultName;

        var environments =
            configuration.Environments?.Select(EnvironmentDefinition.From).ToArray() ??
            Array.Empty<EnvironmentDefinition>();

        var components =
            configuration.Components?.Select(ComponentReferenceDefinition.From).ToArray() ??
            Array.Empty<ComponentReferenceDefinition>();

        var repositories =
            configuration.Repositories?.Select(ComponentRepositoryDefinition.From).ToArray() ??
            Array.Empty<ComponentRepositoryDefinition>();

        var variableProviders =
            configuration.VariableProviders?.Select(VariableProviderDefinition.From).ToArray() ??
            Array.Empty<VariableProviderDefinition>();

        var componentProviders =
            configuration.ComponentProviders?.Select(ComponentProviderDefinition.From).ToArray() ??
            Array.Empty<ComponentProviderDefinition>();

        var configurationFiles =
            configuration.ConfigurationFiles?.Select(ConfigurationFileDefinition.From).ToArray() ??
            Array.Empty<ConfigurationFileDefinition>();

        var subprojects = configuration.Subprojects?.Select(From).ToArray() ??
            Array.Empty<ProjectDefinition>();

        return new ProjectDefinition(
            name,
            environments,
            components,
            repositories,
            variableProviders,
            componentProviders,
            configurationFiles,
            subprojects,
            lastConfigurationFile?.File.Directory);
    }

    public static ProjectDefinition Instance { get; } = new(
        "root",
        Array.Empty<EnvironmentDefinition>(),
        Array.Empty<ComponentReferenceDefinition>(),
        Array.Empty<ComponentRepositoryDefinition>(),
        Array.Empty<VariableProviderDefinition>(),
        Array.Empty<ComponentProviderDefinition>(),
        Array.Empty<ConfigurationFileDefinition>(),
        Array.Empty<ProjectDefinition>(),
        null);
}
