<Project>

    <PropertyGroup>
        <PropsAbove>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))</PropsAbove>
    </PropertyGroup>
    <Import Condition="Exists($(PropsAbove))" Project="$(PropsAbove)"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Confix</RootNamespace>
        <Nullable>enable</Nullable>
        <LangVersion>14.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

</Project>
