using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Confix.CodeGeneration;

/// <summary>
/// Emits an <c>Add{Type}</c> extension for every type declaring a Confix section, so the
/// registration does not have to be written by hand next to each options class.
/// </summary>
[Generator]
public sealed class OptionsExtensionsGenerator : IIncrementalGenerator
{
    private const string SectionAttribute = "Confix.ConfixSectionAttribute";
    private const string ExtensionsType = "Confix.ConfixOptionsExtensions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Without Confix.Options the generated call would not compile.
        var hasExtensions = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypeByMetadataName(ExtensionsType) is not null);

        var types = context.SyntaxProvider
            .ForAttributeWithMetadataName(SectionAttribute,
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
                static (syntaxContext, _) => Describe(syntaxContext))
            .Where(static type => type is not null)
            .Select(static (type, _) => type!);

        context.RegisterSourceOutput(types.Combine(hasExtensions),
            static (production, source) =>
            {
                if (source.Right)
                {
                    Generate(production, source.Left);
                }
            });
    }

    private static OptionsType? Describe(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol
            {
                IsAbstract: false,
                IsGenericType: false,
                ContainingType: null
            } symbol)
        {
            return null;
        }

        if (symbol.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
        {
            return null;
        }

        var arguments = context.Attributes[0].ConstructorArguments;

        var section = arguments.Length > 0 && arguments[0].Value is string path
            ? path
            : string.Empty;

        return new OptionsType(
            symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            MethodName(symbol.Name),
            section,
            symbol.DeclaredAccessibility == Accessibility.Public);
    }

    private static string MethodName(string typeName)
        => typeName.EndsWith("Options", System.StringComparison.Ordinal)
            ? "Add" + typeName
            : "Add" + typeName + "Options";

    private static void Generate(SourceProductionContext context, OptionsType type)
    {
        var qualified = type.Namespace is null
            ? "global::" + type.Name
            : $"global::{type.Namespace}.{type.Name}";

        var accessibility = type.IsPublic ? "public" : "internal";
        var section = type.Section.Length == 0 ? "(root)" : type.Section;
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (type.Namespace is not null)
        {
            builder.AppendLine($"namespace {type.Namespace};");
            builder.AppendLine();
        }

        builder.AppendLine($"{accessibility} static class {type.Name}ConfixExtensions");
        builder.AppendLine("{");
        builder.AppendLine($"    /// <summary>Registers <see cref=\"{qualified}\"/> for the");
        builder.AppendLine($"    /// <c>{section}</c> configuration section.</summary>");
        builder.AppendLine(
            $"    {accessibility} static global::Confix.ConfixOptionsBuilder<{qualified}> {type.MethodName}(");
        builder.AppendLine(
            "        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        builder.AppendLine(
            "        global::Microsoft.Extensions.Configuration.IConfiguration configuration)");
        builder.AppendLine(
            $"        => global::Confix.ConfixOptionsExtensions.AddConfixOptions<{qualified}>(services, configuration);");
        builder.AppendLine("}");

        var hint = type.Namespace is null
            ? $"{type.Name}.ConfixOptions.g.cs"
            : $"{type.Namespace}.{type.Name}.ConfixOptions.g.cs";

        context.AddSource(hint, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private sealed record OptionsType(
        string? Namespace,
        string Name,
        string MethodName,
        string Section,
        bool IsPublic);
}
