<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Configuration contract attributes for Confix.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
